name: 'dbt_airbnb_nyc'
version: '1.0.0'

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  dbt_airbnb_nyc:
    staging:
      +materialized: view
    marts:
      +materialized: table